import { Product, Testimonial } from './types';

export const NAV_LINKS = [
  { name: 'Home', href: '#home' },
  { name: 'Shop', href: '/shop' },
  { name: 'Events', href: '/events' },
  { name: 'How It Works', href: '#how-it-works' },
  { name: 'About', href: '#about' },
  { name: 'Contact', href: '#contact' },
];


export const PRODUCTS: Product[] = [
  // 1 MEAT + 1 SAUCE COMBOS
  {
    id: 'combo-lone-star',
    name: 'Lone Star Solo',
    description: 'Beef Brisket (200g) + 1 Signature Sauce (250ml)',
    longDescription: 'The ultimate Texas power meal. Our signature 12-hour smoked beef brisket paired with your choice of any handcrafted bottle of sauce.',
    price: '₹549',
    priceValue: 549,
    image: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=800&q=80',
    category: 'combo',
    subCategory: 'combos',
    badges: ['Best Seller', 'Pitmaster Choice'],
    heatingInstructions: 'Heat brisket in foil (150°C, 10m). Serve sauce at room temp.',
    relatedProductIds: ['beef-brisket', 'sauce-texas']
  },
  {
    id: 'combo-peri-peri-punch',
    name: 'Peri Peri Punch',
    description: 'Peri Peri Wings (8pcs) + 1 Signature Sauce (250ml)',
    longDescription: 'A citrusy, spicy explosion. Authentic slow-smoked Peri Peri wings served alongside a full 250ml bottle of your favorite sauce.',
    price: '₹379',
    priceValue: 379,
    image: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?auto=format&fit=crop&w=800&q=80',
    category: 'combo',
    subCategory: 'combos',
    badges: ['Spicy Favorite', 'Ready to Serve'],
    heatingInstructions: 'Microwave wings for 2-3 minutes. Shake sauce well.',
    relatedProductIds: ['wings-peri-peri', 'sauce-peri-peri']
  },
  {
    id: 'combo-garlic-glaze',
    name: 'Garlic Glaze Chicken',
    description: 'Pepper Garlic Chicken Steak (200g) + 1 Signature Sauce (250ml)',
    longDescription: 'For the garlic lovers. A juicy, smoke-kissed chicken steak paired with a bottle of our umami-rich signature sauce.',
    price: '₹449',
    priceValue: 449,
    image: 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=800&q=80',
    category: 'combo',
    subCategory: 'combos',
    badges: ['Pitmaster Special', 'Healthy Choice'],
    heatingInstructions: 'Pan-fry chicken steak with a dash of butter. Enjoy with room temp sauce.',
    relatedProductIds: ['chicken-pepper-garlic', 'sauce-pepper-garlic']
  },

  // 2 MEATS + 2 SAUCES COMBOS
  {
    id: 'combo-vanguard-feast',
    name: 'Pitmaster Vanguard',
    description: 'Beef Brisket (200g) + Pork Ribs (200g) + 2 Signature Sauces',
    longDescription: 'The heavy-hitters. A massive combination of our king brisket and fall-off-the-bone ribs, rounded out with two full bottles of sauce for the ultimate variety.',
    price: '₹1099',
    priceValue: 1099,
    image: 'https://images.unsplash.com/photo-1529692236671-f1f6e9460272?auto=format&fit=crop&w=800&q=80',
    category: 'combo',
    subCategory: 'combos',
    badges: ['Maximum Value', 'Family Favorite'],
    heatingInstructions: 'Oven warm ribs in foil (160°C, 10m) and brisket (150°C, 10m).',
    relatedProductIds: ['combo-lone-star', 'pork-ribs']
  },
  {
    id: 'combo-texas-smoked-duo',
    name: 'Texas Smoked Duo',
    description: 'Pork Belly (200g) + Texas Chicken Steak (200g) + 2 Signature Sauces',
    longDescription: 'The perfect double-team. Rich, melting pork belly paired with our signature Texas chicken steak and two bottles of sauce.',
    price: '₹999',
    priceValue: 999,
    image: 'https://images.unsplash.com/photo-1544077960-604201fe74bc?auto=format&fit=crop&w=800&q=80',
    category: 'combo',
    subCategory: 'combos',
    badges: ['Pitmaster Selection', 'Value Pack'],
    heatingInstructions: 'Crisp pork belly on a skillet (2m/side). Oven warm chicken steak.',
    relatedProductIds: ['pork-belly', 'chicken-texas-steak']
  },
  {
    id: 'combo-heatseeker-feast',
    name: 'Double Heatseeker',
    description: 'Spicy Wings (8pcs) + Spicy Pork (200g) + 2 Signature Sauces',
    longDescription: 'For the thrill-seekers. Our fiery wings and smokey spicy pork, locked and loaded with two bottles of our hottest sauces.',
    price: '₹929',
    priceValue: 929,
    image: 'https://images.unsplash.com/photo-1516684732162-798a0062be99?auto=format&fit=crop&w=800&q=80',
    category: 'combo',
    subCategory: 'combos',
    badges: ['Extreme Heat', 'New Arrival'],
    heatingInstructions: 'Heat spicy pork in a wok for 3 minutes. Microwave wings for 2-3 minutes.',
    relatedProductIds: ['wings-bbq-spicy', 'pork-spicy']
  },

  // WINGS
  {
    id: 'wings-texas-saucy',
    name: 'Texas Style Saucy Wings',
    description: 'Classic pitmaster style wings with a rich Texas glaze (8pcs).',
    longDescription: 'Our Texas Style Saucy Wings are slow-smoked over premium charcoal for hours, then tossed in a bold, savory BBQ glaze that captures the heart of Texas BBQ.',
    price: '₹180',
    priceValue: 180,
    image: '/Saucy_Wings.jpg',
    category: 'bbq',
    subCategory: 'wings',
    weight: '8pcs',
    badges: ['Slow Smoked', 'Ready to Heat & Serve'],
    heatingInstructions: 'Microwave for 2 mins or oven bake at 180°C for 5 mins until sizzling.',
    ingredients: 'Chicken wings, signature Texas BBQ glaze, garlic, onion, charcoal smoke.',
    storageInstructions: 'Store in refrigerator at 0-4°C. Good for 5 days.',
    relatedProductIds: ['wings-bbq-spicy', 'sauce-texas']
  },
  {
    id: 'wings-bbq-spicy',
    name: 'BBQ Spicy Wings',
    description: 'Slow smoked wings with a fiery kick (8pcs).',
    longDescription: 'For those who crave heat, these wings are marinated in a spicy BBQ blend and smoked to perfection. Every bite delivers a punch of flavor and fire.',
    price: '₹180',
    priceValue: 180,
    image: 'https://images.unsplash.com/photo-1527477396000-e27163b481c2?auto=format&fit=crop&w=800&q=80',
    category: 'bbq',
    subCategory: 'wings',
    weight: '8pcs',
    badges: ['Slow Smoked', 'Ready to Heat & Serve'],
    heatingInstructions: 'Microwave for 2 mins or pan-sear for a crispy finish.',
    ingredients: 'Chicken wings, cayenne pepper, paprika, molasses, vinegar, spices.',
    storageInstructions: 'Keep chilled. Use within 5 days.',
    relatedProductIds: ['wings-peri-peri', 'sauce-spicy-mango']
  },
  {
    id: 'wings-peri-peri',
    name: 'Peri Peri Wings',
    description: 'Zesty and spicy wings with a citrus punch (8pcs).',
    longDescription: 'Flame-grilled flavor meets slow-smoked tenderness. Our Peri Peri wings are infused with bird\'s eye chili, citrus, and herbs for a refreshing yet spicy experience.',
    price: '₹180',
    priceValue: 180,
    image: 'https://images.unsplash.com/photo-1608039755401-742074f0548d?auto=format&fit=crop&w=800&q=80',
    category: 'bbq',
    subCategory: 'wings',
    weight: '8pcs',
    badges: ['Slow Smoked', 'Ready to Heat & Serve'],
    heatingInstructions: 'Best enjoyed after heating in an oven at 200°C for 4 mins.',
    ingredients: 'Chicken wings, peri-peri chili, lemon juice, garlic, oil, herbs.',
    storageInstructions: 'Store at 0-4°C. Do not freeze after thawing.',
    relatedProductIds: ['sauce-peri-peri']
  },

  // CHICKEN
  {
    id: 'chicken-pepper-garlic',
    name: 'Pepper Garlic Chicken Steak',
    description: 'Tender chicken steak infused with bold pepper and garlic.',
    longDescription: 'A pitmaster favorite. This juicy chicken steak is marinated in crushed black pepper and roasted garlic, then smoked until it reaches peak tenderness.',
    price: '₹250',
    priceValue: 250,
    image: 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=800&q=80',
    category: 'bbq',
    subCategory: 'chicken',
    weight: '200g',
    badges: ['Slow Smoked', 'Ready to Heat & Serve'],
    heatingInstructions: 'Heat on a skillet with a dash of butter for 3-4 mins per side.',
    ingredients: 'Chicken breast, black pepper, roasted garlic, sea salt, olive oil.',
    storageInstructions: 'Keep refrigerated. Consume within 48 hours of opening.',
    relatedProductIds: ['sauce-pepper-garlic', 'beef-pepper-garlic']
  },
  {
    id: 'chicken-texas-steak',
    name: 'Texas Chicken Steak',
    description: 'Classic Texas style smoked chicken steak.',
    longDescription: 'Smoked over premium charcoal, this chicken steak is seasoned with our signature Texas dry rub for an authentic smokehouse flavor.',
    price: '₹250',
    priceValue: 250,
    image: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=800&q=80',
    category: 'bbq',
    subCategory: 'chicken',
    weight: '200g',
    badges: ['Slow Smoked', 'Ready to Heat & Serve'],
    heatingInstructions: 'Heat on a skillet or oven warm for 5 minutes.',
    ingredients: 'Chicken breast, Texas rub, salt, pepper, smoke.',
    storageInstructions: 'Keep refrigerated.',
    relatedProductIds: ['chicken-pepper-garlic', 'beef-steak-texas']
  },

  // BEEF
  {
    id: 'beef-brisket',
    name: 'Beef Brisket',
    description: '12-hour slow smoked signature Texas brisket.',
    longDescription: 'The King of BBQ. Our beef brisket is slow-smoked for 12 hours over oak charcoal, resulting in a deep smoke ring and melt-in-your-mouth texture.',
    price: '₹360',
    priceValue: 360,
    image: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=800&q=80',
    category: 'bbq',
    subCategory: 'beef',
    weight: '200g',
    badges: ['Best Seller', 'Slow Smoked', 'Ready to Heat & Serve'],
    heatingInstructions: 'Wrap in foil and heat in oven at 150°C for 10-15 mins to maintain juiciness.',
    ingredients: 'Premium beef brisket, salt, black pepper, smoke.',
    storageInstructions: 'Vacuum sealed. Keep refrigerated for up to 7 days.',
    relatedProductIds: ['beef-steak-texas', 'sauce-texas']
  },
  {
    id: 'beef-pepper-garlic',
    name: 'Beef Pepper Garlic Steak',
    description: 'Savory beef steak with a robust pepper-garlic crust.',
    longDescription: 'A bold take on beef steak. Sliced from premium cuts, this steak is seasoned with a thick layer of crushed pepper and garlic, then smoked to medium-well perfection.',
    price: '₹360',
    priceValue: 360,
    image: 'https://images.unsplash.com/photo-1546241072-48010ad28c2c?auto=format&fit=crop&w=800&q=80',
    category: 'bbq',
    subCategory: 'beef',
    weight: '200g',
    badges: ['Slow Smoked', 'Ready to Heat & Serve'],
    heatingInstructions: 'Quickly pan-sear for 1-2 mins on each side over high heat.',
    ingredients: 'Beef steak, black pepper, garlic, salt, Worcestershire sauce.',
    storageInstructions: 'Keep at 0-4°C.',
    relatedProductIds: ['chicken-pepper-garlic', 'sauce-pepper-garlic']
  },
  {
    id: 'beef-steak-texas',
    name: 'Texas Beef Steak',
    description: 'Hardcore Texas flavor. Smoked and bold.',
    longDescription: 'Deep, smoky, and intensely flavorful. This beef steak is treated with a traditional Texas rub and smoked over hardwood for a truly authentic ranch experience.',
    price: '₹360',
    priceValue: 360,
    image: 'https://images.unsplash.com/photo-1600891964599-f61ba0e24092?auto=format&fit=crop&w=800&q=80',
    category: 'bbq',
    subCategory: 'beef',
    weight: '200g',
    badges: ['Slow Smoked', 'Ready to Heat & Serve'],
    heatingInstructions: 'Oven bake at 180°C for 6-8 mins or grill for 3 mins.',
    ingredients: 'Beef, paprika, cumin, brown sugar, salt, coffee-infused smoke.',
    storageInstructions: 'Refrigerate immediately.',
    relatedProductIds: ['beef-brisket', 'sauce-texas']
  },

  // PORK
  {
    id: 'pork-ribs',
    name: 'Texas Smoked Pork Ribs',
    description: 'Fall-off-the-bone ribs with a sticky BBQ glaze.',
    longDescription: 'Our award-winning pork ribs are slow-smoked until they are incredibly tender. Finished with a glaze that balances sweet and savory perfectly.',
    price: '₹350',
    priceValue: 350,
    image: '/Pork_Ribs.jpg',
    category: 'bbq',
    subCategory: 'pork',
    weight: '200g',
    badges: ['Most Popular', 'Slow Smoked', 'Ready to Heat & Serve'],
    heatingInstructions: 'Oven bake at 160°C for 10 mins covered with foil.',
    ingredients: 'Pork ribs, BBQ sauce, molasses, apple cider vinegar, salt.',
    storageInstructions: 'Keep chilled. Use within 5 days.',
    relatedProductIds: ['pork-belly', 'sauce-texas']
  },
  {
    id: 'pork-belly',
    name: 'Texas Smoked Pork Belly',
    description: 'Rich, juicy, and smoky pork belly slices.',
    longDescription: 'Decadent layers of fat and meat, smoked slowly to render the fat and infuse deep charcoal flavor. It\'s the ultimate comfort BBQ.',
    price: '₹350',
    priceValue: 350,
    image: 'https://images.unsplash.com/photo-1615937657715-bc7b4b7962c1?auto=format&fit=crop&w=800&q=80',
    category: 'bbq',
    subCategory: 'pork',
    weight: '200g',
    badges: ['Slow Smoked', 'Ready to Heat & Serve'],
    heatingInstructions: 'Pan-fry for 2 mins per side to crisp up the edges.',
    ingredients: 'Pork belly, brown sugar rub, smoked paprika, garlic powder.',
    storageInstructions: 'Store in refrigerator. Consumption within 3 days recommended.',
    relatedProductIds: ['pork-spicy', 'sauce-spicy-mango']
  },
  {
    id: 'pork-spicy',
    name: 'Smokey Spicy Pork',
    description: 'Infused with smoke and fire. A spicy pork delight.',
    longDescription: 'This isn\'t for the faint of heart. Our spicy pork is rubbed with a blend of dried chilies and smoked over hot coals for a lingering, deep heat.',
    price: '₹350',
    priceValue: 350,
    image: 'https://images.unsplash.com/photo-1516684732162-798a0062be99?auto=format&fit=crop&w=800&q=80',
    category: 'bbq',
    subCategory: 'pork',
    weight: '200g',
    badges: ['Slow Smoked', 'Ready to Heat & Serve'],
    heatingInstructions: 'Heat in microwave for 3 mins or stir-fry briefly.',
    ingredients: 'Pork, chili pepper flakes, habanero powder, garlic, vinegar.',
    storageInstructions: 'Keep at 0-4°C.',
    relatedProductIds: ['pork-belly', 'wings-bbq-spicy']
  },

  // SAUCES
  {
    id: 'sauce-texas',
    name: 'Smokey Texas Sauce',
    description: 'Classic pitmaster style. Smokey, rich, authentic.',
    longDescription: 'The heart of the Lone Star State in a bottle. Deep, savory, and perfectly smoky with a rich tomato base and a secret blend of spices that have been a Texas legend for generations.',
    price: '₹220',
    priceValue: 220,
    image: '/smokeytexas_saucebottle.png',
    category: 'sauce',
    subCategory: 'sauces',
    volume: '250ml',
    badges: ['Pitmaster Crafted', 'Best Seller'],
    ingredients: 'Tomato paste, molasses, apple cider vinegar, hickory smoke, secret spice blend.',
    storageInstructions: 'Refrigerate after opening. Shake well before use.',
    relatedProductIds: ['beef-brisket', 'pork-ribs']
  },
  {
    id: 'sauce-saucy-wings',
    name: 'Texas Style Saucy Wings',
    description: 'Bold, tangy, and perfect for wings.',
    longDescription: 'The ultimate wing glaze. Designed specifically for our signature wings, this sauce balances heat, tang, and sweetness for that authentic Texas-style kick.',
    price: '₹220',
    priceValue: 220,
    image: '/saucywings_saucebottle.png',
    category: 'sauce',
    subCategory: 'sauces',
    volume: '250ml',
    badges: ['Pitmaster Crafted', 'Wing King'],
    ingredients: 'Hot sauce base, honey, vinegar, secret spices, butter flavor.',
    storageInstructions: 'Refrigerate after opening.',
    relatedProductIds: ['wings-texas-saucy']
  },
  {
    id: 'sauce-pork-ribs',
    name: 'Pork Ribs Sauce',
    description: 'The perfect companion for ribs.',
    longDescription: 'Engineered specifically for low & slow pork. This sauce penetrates deep into the meat, adding a layer of sweet-smokey complexity that makes ribs truly unforgettable.',
    price: '₹220',
    priceValue: 220,
    image: '/porkribs_saucebottle.png',
    category: 'sauce',
    subCategory: 'sauces',
    volume: '250ml',
    badges: ['Pitmaster Crafted', 'Rib Master'],
    ingredients: 'Tomato concentrate, brown sugar, apple juice, cider vinegar, pork-friendly spice blend.',
    storageInstructions: 'Refrigerate after opening.',
    relatedProductIds: ['pork-ribs']
  },
  {
    id: 'sauce-brisket',
    name: 'The Brisket Sauce',
    description: 'Designed for the King of BBQ.',
    longDescription: 'A sophisticated, less-sweet sauce designed to complement the rich, fatty goodness of slow-smoked beef brisket. Peppery, savory, and bold.',
    price: '₹220',
    priceValue: 220,
    image: '/brisket_saucebottle.png',
    category: 'sauce',
    subCategory: 'sauces',
    volume: '250ml',
    badges: ['Pitmaster Crafted', 'Beef Specialist'],
    ingredients: 'Beef stock, black pepper, garlic, onion, Worcestershire, minimal sugar.',
    storageInstructions: 'Refrigerate after opening.',
    relatedProductIds: ['beef-brisket']
  }
];

export const SAUCES = PRODUCTS.filter(p => p.category === 'sauce');


export const TESTIMONIALS: Testimonial[] = [
  { id: 1, name: 'Rahul K.', text: 'Best brisket in Bangalore, hands down. The smoky flavor is authentic Texas style.', rating: 5 },
  { id: 2, name: 'Sarah J.', text: 'The ribs literally fell off the bone. And that spicy sauce? Incredible.', rating: 5 },
  { id: 3, name: 'Arun M.', text: 'Been coming here since the food truck days in 2011. Quality never drops.', rating: 5 },
];

export const CONTACT_INFO = {
  phone: '7899870957',
  location: 'RS Palaya, Kammanahalli, Bangalore',
  gpay: '9886328867',
  whatsapp: 'https://wa.me/917899870957',
};