import { Product, Testimonial } from './types';

export const NAV_LINKS = [
  { name: 'Home', href: '#home' },
  { name: 'Shop', href: '/shop' },
  { name: 'Events', href: '/events' },
  { name: 'How It Works', href: '#how-it-works' },
  { name: 'About', href: '#about' },
  { name: 'Contact', href: '#contact' },
];


export const PRODUCTS: Product[] = [
  // COMBOS (Top of the list for visibility)
  {
    id: 'combo-pitmaster',
    name: 'Pitmaster Combo',
    description: 'Brisket (250g) + Spicy Wings (250g) + 1 Sauce (250ml)',
    longDescription: 'Our most popular selection. Experience the cornerstone of Texas BBQ with our signature 12-hour smoked brisket, a portion of our fiery wings, and your choice of handcrafted sauce.',
    price: '₹999',
    priceValue: 999,
    image: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=800&q=80',
    category: 'combo',
    subCategory: 'combos',
    badges: ['Most Popular', 'Best Seller', 'Pitmaster Crafted'],
    heatingInstructions: 'Heat brisket in foil (150°C, 10m), microwave wings (2m).',
    relatedProductIds: ['combo-weekend', 'beef-brisket']
  },
  {
    id: 'combo-weekend',
    name: 'Weekend BBQ Combo',
    description: 'Brisket (250g) + Pork Ribs (250g) + Wings (250g) + 1 Sauce',
    longDescription: 'The ultimate weekend treat. This value-packed combo brings the full pit experience to your table. Perfect for a small family or a serious BBQ enthusiast.',
    price: '₹1499',
    priceValue: 1499,
    image: 'https://images.unsplash.com/photo-1544077960-604201fe74bc?auto=format&fit=crop&w=800&q=80',
    category: 'combo',
    subCategory: 'combos',
    badges: ['Best Value', 'Weekend Special', 'Slow Smoked'],
    heatingInstructions: 'Follow individual instructions for brisket, ribs, and wings included in the pack.',
    relatedProductIds: ['combo-family', 'pork-ribs']
  },
  {
    id: 'combo-starter',
    name: 'First Timer Combo',
    description: 'BBQ Spicy Wings (250g) + 1 Signature Sauce (250ml)',
    longDescription: 'New to Smoke Signal? Start here. Our First Timer Combo pairs our zesty, smoked spicy wings with a full bottle of our artisanal sauce.',
    price: '₹699',
    priceValue: 699,
    image: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?auto=format&fit=crop&w=800&q=80',
    category: 'combo',
    subCategory: 'combos',
    badges: ['Perfect Starter Pack', 'New Arrival'],
    heatingInstructions: 'Microwave wings for 2-3 minutes. Serve sauce at room temp or slightly warmed.',
    relatedProductIds: ['combo-pitmaster', 'wings-bbq-spicy']
  },
  {
    id: 'combo-meat-lover',
    name: 'Meat Lover Combo',
    description: 'Beef Brisket (250g) + Pork Belly (350g) + 1 Sauce',
    longDescription: 'A decadent combination of our richest smoked meats. Melt-in-your-mouth brisket paired with juicy, smoke-infused pork belly.',
    price: '₹1299',
    priceValue: 1299,
    image: 'https://images.unsplash.com/photo-1615937657715-bc7b4b7962c1?auto=format&fit=crop&w=800&q=80',
    category: 'combo',
    subCategory: 'combos',
    badges: ['Pitmaster Special', 'Premium Choice'],
    heatingInstructions: 'Pan-fry pork belly (2m/side) and oven-warm brisket in foil.',
    relatedProductIds: ['combo-pitmaster', 'pork-belly']
  },
  {
    id: 'combo-family',
    name: 'Family BBQ Feast',
    description: 'Brisket + Pork Belly + Pork Ribs + Wings + 2 Sauces',
    longDescription: 'Throw a Texas party at home. This massive spread handles the whole family with a variety of textures and heat levels.',
    price: '₹1999',
    priceValue: 1999,
    image: 'https://images.unsplash.com/photo-1529692236671-f1f6e9460272?auto=format&fit=crop&w=800&q=80',
    category: 'combo',
    subCategory: 'combos',
    badges: ['Family Feast', 'Ultimate Value'],
    heatingInstructions: 'Full heating guide included. Recommended to use oven for best results.',
    relatedProductIds: ['combo-ultimate']
  },
  {
    id: 'combo-ultimate',
    name: 'Ultimate Pitmaster Box',
    description: 'Double Brisket + Pork Belly + Pork Ribs + Wings + 2 Sauces',
    longDescription: 'The anchor of our collection. For the true connoisseur who wants it all, and then some. A professional BBQ setup delivered to your door.',
    price: '₹2499',
    priceValue: 2499,
    image: 'https://images.unsplash.com/photo-1600891964599-f61ba0e24092?auto=format&fit=crop&w=800&q=80',
    category: 'combo',
    subCategory: 'combos',
    badges: ['Ultimate BBQ Experience', 'Pitmaster Special'],
    heatingInstructions: 'Comprehensive pitmaster heating guide included.',
    relatedProductIds: ['combo-family']
  },

  // WINGS
  {
    id: 'wings-texas-saucy',
    name: 'Texas Style Saucy Wings',
    description: 'Classic pitmaster style wings with a rich Texas glaze.',
    longDescription: 'Our Texas Style Saucy Wings are slow-smoked over premium charcoal for hours, then tossed in a bold, savory BBQ glaze that captures the heart of Texas BBQ.',
    price: '₹349',
    priceValue: 349,
    image: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?auto=format&fit=crop&w=800&q=80',
    category: 'bbq',
    subCategory: 'wings',
    weight: '250g',
    badges: ['Slow Smoked', 'Ready to Heat & Serve'],
    heatingInstructions: 'Microwave for 2 mins or oven bake at 180°C for 5 mins until sizzling.',
    ingredients: 'Chicken wings, signature Texas BBQ glaze, garlic, onion, charcoal smoke.',
    storageInstructions: 'Store in refrigerator at 0-4°C. Good for 5 days.',
    relatedProductIds: ['wings-bbq-spicy', 'sauce-texas']
  },
  {
    id: 'wings-bbq-spicy',
    name: 'BBQ Spicy Wings',
    description: 'Slow smoked wings with a fiery kick.',
    longDescription: 'For those who crave heat, these wings are marinated in a spicy BBQ blend and smoked to perfection. Every bite delivers a punch of flavor and fire.',
    price: '₹349',
    priceValue: 349,
    image: 'https://images.unsplash.com/photo-1527477396000-e27163b481c2?auto=format&fit=crop&w=800&q=80',
    category: 'bbq',
    subCategory: 'wings',
    weight: '250g',
    badges: ['Slow Smoked', 'Ready to Heat & Serve'],
    heatingInstructions: 'Microwave for 2 mins or pan-sear for a crispy finish.',
    ingredients: 'Chicken wings, cayenne pepper, paprika, molasses, vinegar, spices.',
    storageInstructions: 'Keep chilled. Use within 5 days.',
    relatedProductIds: ['wings-peri-peri', 'sauce-spicy-mango']
  },
  {
    id: 'wings-peri-peri',
    name: 'Peri Peri Wings',
    description: 'Zesty and spicy wings with a citrus punch.',
    longDescription: 'Flame-grilled flavor meets slow-smoked tenderness. Our Peri Peri wings are infused with bird\'s eye chili, citrus, and herbs for a refreshing yet spicy experience.',
    price: '₹349',
    priceValue: 349,
    image: 'https://images.unsplash.com/photo-1608039755401-742074f0548d?auto=format&fit=crop&w=800&q=80',
    category: 'bbq',
    subCategory: 'wings',
    weight: '250g',
    badges: ['Slow Smoked', 'Ready to Heat & Serve'],
    heatingInstructions: 'Best enjoyed after heating in an oven at 200°C for 4 mins.',
    ingredients: 'Chicken wings, peri-peri chili, lemon juice, garlic, oil, herbs.',
    storageInstructions: 'Store at 0-4°C. Do not freeze after thawing.',
    relatedProductIds: ['sauce-peri-peri']
  },

  // CHICKEN
  {
    id: 'chicken-pepper-garlic',
    name: 'Pepper Garlic Chicken Steak',
    description: 'Tender chicken steak infused with bold pepper and garlic.',
    longDescription: 'A pitmaster favorite. This juicy chicken steak is marinated in crushed black pepper and roasted garlic, then smoked until it reaches peak tenderness.',
    price: '₹449',
    priceValue: 449,
    image: 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=800&q=80',
    category: 'bbq',
    subCategory: 'chicken',
    weight: '250g',
    badges: ['Slow Smoked', 'Ready to Heat & Serve'],
    heatingInstructions: 'Heat on a skillet with a dash of butter for 3-4 mins per side.',
    ingredients: 'Chicken breast, black pepper, roasted garlic, sea salt, olive oil.',
    storageInstructions: 'Keep refrigerated. Consume within 48 hours of opening.',
    relatedProductIds: ['sauce-pepper-garlic', 'beef-pepper-garlic']
  },

  // BEEF
  {
    id: 'beef-brisket',
    name: 'Beef Brisket',
    description: '12-hour slow smoked signature Texas brisket.',
    longDescription: 'The King of BBQ. Our beef brisket is slow-smoked for 12 hours over oak charcoal, resulting in a deep smoke ring and melt-in-your-mouth texture.',
    price: '₹649',
    priceValue: 649,
    image: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=800&q=80',
    category: 'bbq',
    subCategory: 'beef',
    weight: '250g',
    badges: ['Best Seller', 'Slow Smoked', 'Ready to Heat & Serve'],
    heatingInstructions: 'Wrap in foil and heat in oven at 150°C for 10-15 mins to maintain juiciness.',
    ingredients: 'Premium beef brisket, salt, black pepper, smoke.',
    storageInstructions: 'Vacuum sealed. Keep refrigerated for up to 7 days.',
    relatedProductIds: ['beef-steak-texas', 'sauce-texas']
  },
  {
    id: 'beef-pepper-garlic',
    name: 'Beef Pepper Garlic Steak',
    description: 'Savory beef steak with a robust pepper-garlic crust.',
    longDescription: 'A bold take on beef steak. Sliced from premium cuts, this steak is seasoned with a thick layer of crushed pepper and garlic, then smoked to medium-well perfection.',
    price: '₹599',
    priceValue: 599,
    image: 'https://images.unsplash.com/photo-1546241072-48010ad28c2c?auto=format&fit=crop&w=800&q=80',
    category: 'bbq',
    subCategory: 'beef',
    weight: '250g',
    badges: ['Slow Smoked', 'Ready to Heat & Serve'],
    heatingInstructions: 'Quickly pan-sear for 1-2 mins on each side over high heat.',
    ingredients: 'Beef steak, black pepper, garlic, salt, Worcestershire sauce.',
    storageInstructions: 'Keep at 0-4°C.',
    relatedProductIds: ['chicken-pepper-garlic', 'sauce-pepper-garlic']
  },
  {
    id: 'beef-steak-texas',
    name: 'Texas Beef Steak',
    description: 'Hardcore Texas flavor. Smoked and bold.',
    longDescription: 'Deep, smoky, and intensely flavorful. This beef steak is treated with a traditional Texas rub and smoked over hardwood for a truly authentic ranch experience.',
    price: '₹599',
    priceValue: 599,
    image: 'https://images.unsplash.com/photo-1600891964599-f61ba0e24092?auto=format&fit=crop&w=800&q=80',
    category: 'bbq',
    subCategory: 'beef',
    weight: '250g',
    badges: ['Slow Smoked', 'Ready to Heat & Serve'],
    heatingInstructions: 'Oven bake at 180°C for 6-8 mins or grill for 3 mins.',
    ingredients: 'Beef, paprika, cumin, brown sugar, salt, coffee-infused smoke.',
    storageInstructions: 'Refrigerate immediately.',
    relatedProductIds: ['beef-brisket', 'sauce-texas']
  },

  // PORK
  {
    id: 'pork-ribs',
    name: 'Texas Smoked Pork Ribs',
    description: 'Fall-off-the-bone ribs with a sticky BBQ glaze.',
    longDescription: 'Our award-winning pork ribs are slow-smoked until they are incredibly tender. Finished with a glaze that balances sweet and savory perfectly.',
    price: '₹599',
    priceValue: 599,
    image: 'https://images.unsplash.com/photo-1544077960-604201fe74bc?auto=format&fit=crop&w=800&q=80',
    category: 'bbq',
    subCategory: 'pork',
    weight: '250g',
    badges: ['Most Popular', 'Slow Smoked', 'Ready to Heat & Serve'],
    heatingInstructions: 'Oven bake at 160°C for 10 mins covered with foil.',
    ingredients: 'Pork ribs, BBQ sauce, molasses, apple cider vinegar, salt.',
    storageInstructions: 'Keep chilled. Use within 5 days.',
    relatedProductIds: ['pork-belly', 'sauce-texas']
  },
  {
    id: 'pork-belly',
    name: 'Texas Smoked Pork Belly',
    description: 'Rich, juicy, and smoky pork belly slices.',
    longDescription: 'Decadent layers of fat and meat, smoked slowly to render the fat and infuse deep charcoal flavor. It\'s the ultimate comfort BBQ.',
    price: '₹549',
    priceValue: 549,
    image: 'https://images.unsplash.com/photo-1615937657715-bc7b4b7962c1?auto=format&fit=crop&w=800&q=80',
    category: 'bbq',
    subCategory: 'pork',
    weight: '350g',
    badges: ['Slow Smoked', 'Ready to Heat & Serve'],
    heatingInstructions: 'Pan-fry for 2 mins per side to crisp up the edges.',
    ingredients: 'Pork belly, brown sugar rub, smoked paprika, garlic powder.',
    storageInstructions: 'Store in refrigerator. Consumption within 3 days recommended.',
    relatedProductIds: ['pork-spicy', 'sauce-spicy-mango']
  },
  {
    id: 'pork-spicy',
    name: 'Smokey Spicy Pork',
    description: 'Infused with smoke and fire. A spicy pork delight.',
    longDescription: 'This isn\'t for the faint of heart. Our spicy pork is rubbed with a blend of dried chilies and smoked over hot coals for a lingering, deep heat.',
    price: '₹449',
    priceValue: 449,
    image: 'https://images.unsplash.com/photo-1516684732162-798a0062be99?auto=format&fit=crop&w=800&q=80',
    category: 'bbq',
    subCategory: 'pork',
    weight: '350g',
    badges: ['Slow Smoked', 'Ready to Heat & Serve'],
    heatingInstructions: 'Heat in microwave for 3 mins or stir-fry briefly.',
    ingredients: 'Pork, chili pepper flakes, habanero powder, garlic, vinegar.',
    storageInstructions: 'Keep at 0-4°C.',
    relatedProductIds: ['pork-belly', 'wings-bbq-spicy']
  },

  // SAUCES
  {
    id: 'sauce-texas',
    name: 'BBQ Texas Sauce',
    description: 'Classic pitmaster style. Smoky, rich, authentic.',
    longDescription: 'The one that started it all. A balanced blend of tang, sweetness, and deep smoke. Perfect for brisket, ribs, or as a dipping sauce.',
    price: '₹249',
    priceValue: 249,
    image: 'https://images.unsplash.com/photo-1585325701956-60dd9c8524bc?auto=format&fit=crop&w=800&q=80',
    category: 'sauce',
    subCategory: 'sauces',
    volume: '250ml',
    badges: ['Pitmaster Crafted'],
    ingredients: 'Tomato paste, molasses, apple cider vinegar, hickory smoke, secret spice blend.',
    storageInstructions: 'Refrigerate after opening. Shake well before use.',
    relatedProductIds: ['beef-brisket', 'pork-ribs']
  },
  {
    id: 'sauce-spicy-mango',
    name: 'BBQ Spicy Mango Sauce',
    description: 'Sweet, tangy, and spicy fusion sauce.',
    longDescription: 'A tropical twist on traditional BBQ. Real mango pulp blended with habanero peppers for a sauce that\'s sweet up front with a kick at the end.',
    price: '₹249',
    priceValue: 249,
    image: 'https://images.unsplash.com/photo-1478144592103-258219070793?auto=format&fit=crop&w=800&q=80',
    category: 'sauce',
    subCategory: 'sauces',
    volume: '250ml',
    badges: ['Pitmaster Crafted'],
    ingredients: 'Mango pulp, habanero peppers, honey, vinegar, lime juice, ginger.',
    storageInstructions: 'Refrigerate after opening.',
    relatedProductIds: ['wings-bbq-spicy', 'pork-spicy']
  },
  {
    id: 'sauce-pepper-garlic',
    name: 'Smokey Pepper Garlic Sauce',
    description: 'Savory, smoky garlic pepper flavor.',
    longDescription: 'A heavy-hitter for garlic lovers. This sauce features roasted garlic cloves and cracked black pepper for a savory, umami-rich experience.',
    price: '₹249',
    priceValue: 249,
    image: 'https://images.unsplash.com/photo-1631402242084-3c66289f81da?auto=format&fit=crop&w=800&q=80',
    category: 'sauce',
    subCategory: 'sauces',
    volume: '250ml',
    badges: ['Pitmaster Crafted'],
    ingredients: 'Roasted garlic, black pepper, onion powder, vinegar, sunflower oil, smoke flavoring.',
    storageInstructions: 'Refrigerate after opening.',
    relatedProductIds: ['chicken-pepper-garlic', 'beef-pepper-garlic']
  },
  {
    id: 'sauce-peri-peri',
    name: 'Peri Peri Sauce',
    description: 'Flame-grilled flavor. Zesty and spicy.',
    longDescription: 'Authentic Peri Peri flavor with a smoky undertone. Made with real bird\'s eye chilies and toasted spices.',
    price: '₹249',
    priceValue: 249,
    image: 'https://images.unsplash.com/photo-1598511796318-7b82ea7bc88c?auto=format&fit=crop&w=800&q=80',
    category: 'sauce',
    subCategory: 'sauces',
    volume: '250ml',
    badges: ['Pitmaster Crafted'],
    ingredients: 'Bird\'s eye chili, lemon, garlic, paprika, oregano, oil.',
    storageInstructions: 'Refrigerate after opening.',
    relatedProductIds: ['wings-peri-peri']
  }
];

export const SAUCES = PRODUCTS.filter(p => p.category === 'sauce');


export const TESTIMONIALS: Testimonial[] = [
  { id: 1, name: 'Rahul K.', text: 'Best brisket in Bangalore, hands down. The smoky flavor is authentic Texas style.', rating: 5 },
  { id: 2, name: 'Sarah J.', text: 'The ribs literally fell off the bone. And that spicy sauce? Incredible.', rating: 5 },
  { id: 3, name: 'Arun M.', text: 'Been coming here since the food truck days in 2011. Quality never drops.', rating: 5 },
];

export const CONTACT_INFO = {
  phone: '7899870957',
  location: 'RS Palaya, Kammanahalli, Bangalore',
  gpay: '9886328867',
  whatsapp: 'https://wa.me/917899870957',
};